name: Tests

on:
    pull_request:
    push:
        branches:
        - master

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        args:
        - "--resolver nightly-2024-03-08"

    steps:
      - name: Clone project
        uses: actions/checkout@v2

# Getting weird OS X errors...
#      - name: Cache dependencies
#        uses: actions/cache@v1
#        with:
#          path: ~/.stack
#          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}
#          restore-keys: |
#            ${{ runner.os }}-${{ matrix.resolver }}-

      - name: Install stack if needed
        shell: bash
        run: |
            set -ex
            if [[ "${{ matrix.os }}" == "macos-latest" ]]
            then
                # macos-latest does not include Haskell tools as of 2024-05-06.
              curl -sSL https://get.haskellstack.org/ | sh
            fi

      - name: Build and run tests
        shell: bash
        run: |
            set -ex
            stack --version
            stack test --fast --no-terminal ${{ matrix.args }}
